export const GET_ERRORS = 'GET_ERRORS';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const CLEAR_CURRENT_PAGE = 'CLEAR_CURRENT_PAGE';
export const IS_MOBILE_BROWSER = 'IS_MOBILE_BROWSER';
export const CLEAR_IS_MOBILE_BROWSER = 'CLEAR_IS_MOBILE_BROWSER';
